// Task 1, Associative array that simulates a database of books
// Thank god for the autogenerated IDs
const bookArray =[
	{id_book:1, name: "Mikael Karvajalka", author: "Mika Waltari", isbn: "082305648z" },
	{id_book:2, name: "Mikael Hakim", author: "Mika Waltari", isbn: "082305650z" },
	{id_book:3, name: "Sinuhe egyptiläinen", author: "Mika Waltari", isbn: "082305649z"},
	{id_book:4, name: "Täällä Pohjantähden alla", author: "Väinö Linna", isbn: "082305651z" },
	{id_book:5, name: "Täällä Pohjantähden alla II", author: "Väinö Linna", isbn: "082305652z" }
];

// Task 2, Print out the type of the array.
console.log(typeof bookArray, '\n');

// Task 3, Print out the contents of the array.
console.log(bookArray, '\n');

// Task 4, Print out the first element of the array.
console.log(bookArray[0], '\n');

// Task 5, Print out the name of the first book in the array.
console.log(bookArray[0].name, '\n');

// Task 6, Print the amount of elements in the array.
console.log(bookArray.length, '\n');

// Task 7, Loop through the array and print out the name of each book.
for (let i = 0; i < bookArray.length; i++) {
	console.log(bookArray[i].name);
}